name: push-schema-to-dev

on:
  push:
    branches: [dev]
    paths: ["prisma/schema.prisma"]

jobs:
  deploy-migrations-to-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.8.1]
    steps:
      - name: Print event
        run: echo ${{ github.event_name }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo DATABASE_URL=${{ secrets.PSCALE_DEV_DATABASE_URL }} > .env

      - name: Install npm ${{ matrix.node-version }}
        uses: npm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Push schema changes
        run: npx prisma db push
