version: "3"

services:
  web:
    container_name: millennicare-web
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    network_mode: "host"
  dev-db:
    container_name: millennicare-dev-database
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: millennicare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
