# version: "3"

# services:
#   web:
#     container_name: nextjs
#     build:
#       context: .
#       dockerfile: ./apps/nextjs/Dockerfile
#       args:
#         - PROJECT: nextjs
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - 3000:3000
#     network_mode: "host"

version: "3"

services:
  web:
    container_name: nextjs
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_LOCATION_API_KEY=${AWS_LOCATION_API_KEY}
      - AWS_LOCATION_SUGGESTION_KEY=${AWS_LOCATION_SUGGESTION_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SESSION_PASSWORD=${SESSION_PASSWORD}
      - SYMMETRIC_KEY=${SYMMETRIC_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - TURBO_TOKEN=${TURBO_TOKEN}
      - TURBO_TEAM=${TURBO_TEAM}
    ports:
      - 3000:3000
