version: "3"

services:
  prod-web:
    container_name: millennicare-web
    image: millennicare-prod
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    env_file:
      - .env
  dev-web:
    container_name: millennicare-dev-web
    image: millennicare-dev
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
      args:
        - NODE_ENV=development
    restart: always
    env_file:
      - .env
  dev-db:
    container_name: millennicare-dev-database
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: millennicare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
