name: Create a database branch
on: create

jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Create a branch
        uses: planetscale/create-branch-action@v1
        id: create_branch
        with:
          org_name: ${{ secrets.PSCALE_ORG}}
          database_name: ${{ secrets.PSCALE_DATABASE_NAME }}
          branch_name: ${{ steps.extract_branch.outputs.branch }}
          from: main
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Create a password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: ${{ secrets.PSCALE_ORG}}
          database_name: ${{ secrets.PSCALE_DATABASE_NAME }}
          branch_name: ${{ steps.extract_branch.outputs.branch }}
          name: "pass_${{ steps.extract_branch.outputs.branch }}"
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Get the new credentials
        run: |
          echo "Hostname: ${{ steps.create_password.outputs.hostname }}"
          echo "Username: ${{ steps.create_password.outputs.username }}"
          echo "Password: ${{ steps.create_password.outputs.password }}"
