name: Create a branch
on:
  pull_request:
    types: [opened]

jobs:
  create_deploy_request:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pscale
        uses: planetscale/setup-pscale-action@v1
      - name: Use pscale
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
        run: |
          pscale deploy-request list ${{ secrets.PSCALE_DATABASE_NAME }} --org ${{ secrets.PSCALE_ORG }}
      - name: checkout
        uses: actions/checkout@v3
      - name: Create a deploy request
        uses: planetscale/create-deploy-request-action@v2
        id: create_deploy_request
        with:
          org_name: ${{ secrets.PSCALE_ORG }}
          database_name: ${{ secrets.PSCALE_DATABASE_NAME }}
          branch_name: dev
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
      - name: Get the deploy request number
        run: |
          echo "Deploy request number: ${{ steps.create_deploy_request.outputs.number }}"
