name: push-schema-to-dev

on:
  push:
    branches: [dev]
    paths: ["packages/db/schema"]

jobs:
  deploy-migrations-to-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.10.1]
    steps:
      - name: Print event
        run: echo ${{ github.event_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo DATABASE_URL=${{ secrets.PSCALE_DEV_DATABASE_URL }} > .env

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Push schema changes
        run: pnpm db:push
